# .streamlit/secrets.toml 

mongo_uri = "mongodb+srv://TAK_USER:Arpith%2692@cluster0.ewncl10.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

OPENAI_API_KEY = "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"

org_logo_path = ".streamlit/logo.png"
org_sign_path = ".streamlit/signature.png"

[users]
Arpith  = "Arpith&92"
Reena   = "Reena&90"
Teena   = "Teena@123"
Kuldeep = "Kuldeep&96"
