# .streamlit/secrets.toml 

mongo_uri = "mongodb+srv://TAK_USER:Arpith%2692@cluster0.ewncl10.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

org_logo_path = ".streamlit/logo.png"
org_sign_path = ".streamlit/signature.png"

[users]
Arpith  = "Arpith&92"
Reena   = "Reena&90"
Teena   = "Teena@123"
Kuldeep = "Kuldeep&96"
